<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <AssemblyName>GameFpsBooster</AssemblyName>
    <RootNamespace>GameFpsBooster</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <Product>Game FPS Booster</Product>
    <AssemblyTitle>Game FPS Booster</AssemblyTitle>
    <Company>Game FPS Booster</Company>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

</Project>
